apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dark-makers-org.fullname" . }}-db
  namespace: dark-makers
  labels:
    {{- include "dark-makers-org.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "dark-makers-org.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: database
  template:
    metadata:
      labels:
        {{- include "dark-makers-org.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: database
    spec:
      containers:
        - name: db
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: {{ include "dark-makers-org.fullname" . }}
          volumeMounts:
            - name: db-data
              mountPath: /var/lib/postgresql/data
              subPath: data
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - {{ .Values.db.user }}
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources.db | nindent 12 }}
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: {{ include "dark-makers-org.fullname" . }}-db
