apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dark-makers-org.fullname" . }}-db
  namespace: dark-makers
  labels:
    {{- include "dark-makers-org.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.db.storage }}
