{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dark-makers-org.fullname" . }}
  namespace: dark-makers
  labels:
    {{- include "dark-makers-org.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: http
    kubernetes.io/ingress.class: traefik
    kubernetes.io/tls-acme: "true"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.hosts }}
    - hosts:
        - {{ . }}
      secretName: {{ include "dark-makers-org.fullname" $ }}-{{ . | replace "." "-" }}-tls
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "dark-makers-org.fullname" $ }}-strapi
                port:
                  number: {{ $.Values.service.port }}
    {{- end }}
{{- end }}
