apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dark-makers-org.fullname" . }}
  namespace: dark-makers
  labels:
    {{- include "dark-makers-org.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "dark-makers-org.databaseUrl" . | quote }}
  DATABASE_CLIENT: "postgres"
  POSTGRES_USER: {{ .Values.db.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.password | quote }}
  POSTGRES_DB: {{ .Values.db.name | quote }}
  HOST: "0.0.0.0"
  PORT: "1337"
  NODE_ENV: "production"
  APP_KEYS: {{ .Values.strapi.appKeys | quote }}
  API_TOKEN_SALT: {{ .Values.strapi.apiTokenSalt | quote }}
  ADMIN_JWT_SECRET: {{ .Values.strapi.adminJwtSecret | quote }}
  TRANSFER_TOKEN_SALT: {{ .Values.strapi.transferTokenSalt | quote }}
  JWT_SECRET: {{ .Values.strapi.jwtSecret | quote }}
