apiVersion: v1
kind: Service
metadata:
  name: {{ include "dark-makers-org.fullname" . }}-strapi
  namespace: dark-makers
  labels:
    {{- include "dark-makers-org.labels" . | nindent 4 }}
    app.kubernetes.io/component: strapi
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1337
  selector:
    {{- include "dark-makers-org.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: strapi
